---
version: '3'
services:

# START SERVICE nginx.rewrite
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.nginx.rewrite:1.17.3
    environment: ['CONTECO_NGINX_CONF_LOCATION=/swarm/ekg/elasticsearch', 'CONTECO_NGINX_CONF_PROXY_PASS=swarm_g1_ekg_elasticsearch:9200']
    command: []
    volumes: []
    ports: []
    networks: [modeco_overlay, swarm_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [traefik.enable=true,traefik.docker.network=modeco_overlay, traefik.http.services.swarm_g1_ekg_elasticsearch.loadbalancer.server.port=80, traefik.http.routers.swarm_g1_ekg_elasticsearch.entrypoints=conteco, traefik.http.routers.swarm_g1_ekg_elasticsearch.rule=PathPrefix("/swarm/ekg/elasticsearch")]
# END SERVICE nginx.rewrite

volumes: {}
networks: {modeco_overlay: { external: true }, swarm_overlay: { external: true }}
