#!/usr/bi/env bash

export CONTECO_LABEL="swarm.g1 - ModEco"
export CONTECO_DESCRIPTION="The swarm monitoring module, main package."

export CONTECO_TYPE="swarm"
export CONTECO_NAME="g1"
export CONTECO_TAG="v3.0.2"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
