#!/usr/bin/env bash


prefix="swarm_$2"

if [[ "swarm_g1_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_ekg_elasticsearch_volume
	fi
	
if [[ "swarm_g1_ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_ekg_grafana_volume
	fi
	
if [[ "swarm_g1_ingest_container_logs_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_ingest_container_logs_filebeat_volume
	fi
	
if [[ "swarm_g1_ingest_container_settings_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_ingest_container_settings_filebeat_volume
	fi
	
if [[ "swarm_g1_ingest_journalctl_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_ingest_journalctl_filebeat_volume
	fi
	
if [[ "swarm_g1_kz_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_kz_kafka_secrets_volume
	fi
	
if [[ "swarm_g1_kz_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_kz_kafka_data_volume
	fi
	
if [[ "swarm_g1_kz_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_secrets_volume
	fi
	
if [[ "swarm_g1_kz_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_data_volume
	fi
	
if [[ "swarm_g1_kz_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_kz_zookeeper_log_volume
	fi
	
if [[ "swarm_g1_metrics_node_metrics_node_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_metrics_node_metrics_node_volume
	fi
	
if [[ "swarm_g1_metrics_overlay_metrics_overlay_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_metrics_overlay_metrics_overlay_volume
	fi
	
if [[ "swarm_g1_export_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_export_streamsets_volume
	fi
	
if [[ "swarm_g1_processor_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create swarm_g1_processor_streamsets_volume
	fi
	
if [[ "swarm_g1_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_ekg_elasticsearch_volume.tar
		fi
		
if [[ "swarm_g1_ekg_grafana_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_ekg_grafana_volume:/var/lib/grafana ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_ekg_grafana_volume.tar
		fi
		
if [[ "swarm_g1_export_streamsets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_export_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_export_streamsets_volume.tar
		fi
		
if [[ "swarm_g1_processor_streamsets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_processor_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_processor_streamsets_volume.tar
		fi
		
