#!/usr/bin/env bash


prefix="swarm_$2"


executionplane --silent docker container prune --force

if [[ "swarm_g1_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_ekg_elasticsearch_volume"
			result=$(docker volume ls | grep "swarm_g1_ekg_elasticsearch_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_ekg_grafana_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_ekg_grafana_volume"
			result=$(docker volume ls | grep "swarm_g1_ekg_grafana_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_ingest_container_logs_filebeat_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_ingest_container_logs_filebeat_volume"
			result=$(docker volume ls | grep "swarm_g1_ingest_container_logs_filebeat_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_ingest_container_settings_filebeat_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_ingest_container_settings_filebeat_volume"
			result=$(docker volume ls | grep "swarm_g1_ingest_container_settings_filebeat_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_ingest_journalctl_filebeat_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_ingest_journalctl_filebeat_volume"
			result=$(docker volume ls | grep "swarm_g1_ingest_journalctl_filebeat_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_kz_kafka_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_kz_kafka_secrets_volume"
			result=$(docker volume ls | grep "swarm_g1_kz_kafka_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_kz_kafka_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_kz_kafka_data_volume"
			result=$(docker volume ls | grep "swarm_g1_kz_kafka_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_kz_zookeeper_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_kz_zookeeper_secrets_volume"
			result=$(docker volume ls | grep "swarm_g1_kz_zookeeper_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_kz_zookeeper_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_kz_zookeeper_data_volume"
			result=$(docker volume ls | grep "swarm_g1_kz_zookeeper_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_kz_zookeeper_log_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_kz_zookeeper_log_volume"
			result=$(docker volume ls | grep "swarm_g1_kz_zookeeper_log_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_metrics_node_metrics_node_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_metrics_node_metrics_node_volume"
			result=$(docker volume ls | grep "swarm_g1_metrics_node_metrics_node_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_metrics_overlay_metrics_overlay_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_metrics_overlay_metrics_overlay_volume"
			result=$(docker volume ls | grep "swarm_g1_metrics_overlay_metrics_overlay_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_export_streamsets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_export_streamsets_volume"
			result=$(docker volume ls | grep "swarm_g1_export_streamsets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "swarm_g1_processor_streamsets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "swarm_g1_processor_streamsets_volume"
			result=$(docker volume ls | grep "swarm_g1_processor_streamsets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
