#!/usr/bin/env bash


prefix="swarm_$2"

if [[ "_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _elasticsearch_volume
	fi
	
if [[ "_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _grafana_volume
	fi
	
if [[ "_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _filebeat_volume
	fi
	
if [[ "_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _filebeat_volume
	fi
	
if [[ "_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _filebeat_volume
	fi
	
if [[ "_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_secrets_volume
	fi
	
if [[ "_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_data_volume
	fi
	
if [[ "_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_secrets_volume
	fi
	
if [[ "_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_data_volume
	fi
	
if [[ "_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_log_volume
	fi
	
if [[ "_metrics_node_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _metrics_node_volume
	fi
	
if [[ "_metrics_overlay_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _metrics_overlay_volume
	fi
	
if [[ "_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _streamsets_volume
	fi
	
if [[ "_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _streamsets_volume
	fi
	
if [[ "swarm_g1_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_ekg_elasticsearch_volume.tar
		fi
		
if [[ "swarm_g1_ekg_grafana_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_ekg_grafana_volume:/var/lib/grafana ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_ekg_grafana_volume.tar
		fi
		
if [[ "swarm_g1_export_streamsets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_export_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_export_streamsets_volume.tar
		fi
		
if [[ "swarm_g1_processor_streamsets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v swarm_g1_processor_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/swarm_g1_processor_streamsets_volume.tar
		fi
		
